spring.datasource.url=${DB_URL:test}
spring.datasource.username=${DB_USER:test}
spring.datasource.password=${DB_PASSWORD:test}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080